import { useMemo } from 'react'
import {
  useShowToolbar,
  useContainerClasses,
  useEffectiveStyle,
  type DataTablePropsParams,
} from './datatable-defaults'

export function useDataTableMemoizedProps<TData>(
  p: DataTablePropsParams<TData>,
) {
  const {
    props,
    visibleColumns,
    processedData,
    currentDensity,
    isFullscreen,
    selectedCount,
    bulkActionsContent,
    handleExport,
    handleDensityChange,
    handleRefresh,
    handleCopy,
    handlePrint,
    clearSelection,
    toggleFullscreen,
    isCopyEnabled,
    isPrintEnabled,
    selectionState,
    expansionState,
    toggleRowSelection,
    toggleRowExpansion,
    toggleSort,
    getSortDirection,
    isAllSelected,
    isSomeSelected,
    selectAllRows,
  } = p
  const {
    data,
    columns,
    getRowId,
    selection,
    expansion,
    pagination,
    sorting,
    filter,
    columnVisibility,
    style,
    export: xCfg,
    isLoading,
    isPending,
    emptyMessage,
    emptyIcon,
    onRowClick,
    onRowDoubleClick,
    onRowContextMenu,
    toolbarConfig,
    headerActions,
    className,
    containerClassName,
    headerClassName,
    bodyClassName,
    rowClassName,
    paginationClassName,
    toolbarClassName,
    fullscreen: fsCfg,
  } = props

  const showToolbar = useShowToolbar(props)
  const effectiveStyle = useEffectiveStyle(style, currentDensity)
  const { containerClass, tableContainerClass, containerStyle } =
    useContainerClasses(
      isFullscreen,
      className,
      containerClassName,
      style?.maxHeight,
      style?.minHeight,
    )

  const toolbarProps = useMemo(
    () => ({
      filter,
      exportConfig: xCfg,
      onExport: handleExport,
      columnVisibility,
      columns,
      selectedCount,
      totalRows: pagination?.totalRows ?? data.length,
      bulkActions: bulkActionsContent,
      headerActions,
      onClearSelection: clearSelection,
      toolbarConfig,
      density: currentDensity,
      onDensityChange: handleDensityChange,
      onRefresh: toolbarConfig?.onRefresh ? handleRefresh : undefined,
      isRefreshing: isPending,
      onCopy: isCopyEnabled ? handleCopy : undefined,
      isCopyEnabled,
      onPrint: isPrintEnabled ? handlePrint : undefined,
      isPrintEnabled,
      isFullscreen,
      onToggleFullscreen: fsCfg?.enabled ? toggleFullscreen : undefined,
      isFullscreenEnabled: fsCfg?.enabled ?? false,
      className: toolbarClassName,
    }),
    [
      filter,
      xCfg,
      handleExport,
      columnVisibility,
      columns,
      selectedCount,
      pagination?.totalRows,
      data.length,
      bulkActionsContent,
      headerActions,
      clearSelection,
      toolbarConfig,
      currentDensity,
      handleDensityChange,
      handleRefresh,
      isPending,
      isCopyEnabled,
      handleCopy,
      isPrintEnabled,
      handlePrint,
      isFullscreen,
      fsCfg?.enabled,
      toggleFullscreen,
      toolbarClassName,
    ],
  )

  const headerProps = useMemo(
    () => ({
      columns: visibleColumns,
      selection,
      showExpander: expansion?.enabled ?? false,
      sorting: sorting?.sorting,
      onSort: toggleSort,
      getSortDirection,
      isAllSelected,
      isSomeSelected,
      onSelectAll: selectAllRows,
      onClearSelection: clearSelection,
      stickyHeader: style?.stickyHeader,
      className: headerClassName,
    }),
    [
      visibleColumns,
      selection,
      expansion?.enabled,
      sorting?.sorting,
      toggleSort,
      getSortDirection,
      isAllSelected,
      isSomeSelected,
      selectAllRows,
      clearSelection,
      style?.stickyHeader,
      headerClassName,
    ],
  )

  const bodyProps = useMemo(
    () => ({
      data: processedData,
      columns: visibleColumns,
      getRowId,
      selection,
      expansion,
      style: effectiveStyle,
      isLoading,
      isPending,
      emptyMessage,
      emptyIcon,
      selectionState,
      expansionState,
      onToggleSelection: toggleRowSelection,
      onToggleExpansion: toggleRowExpansion,
      onRowClick,
      onRowDoubleClick,
      onRowContextMenu,
      rowClassName,
      pageSize: pagination?.pageSize ?? 10,
      className: bodyClassName,
    }),
    [
      processedData,
      visibleColumns,
      getRowId,
      selection,
      expansion,
      effectiveStyle,
      isLoading,
      isPending,
      emptyMessage,
      emptyIcon,
      selectionState,
      expansionState,
      toggleRowSelection,
      toggleRowExpansion,
      onRowClick,
      onRowDoubleClick,
      onRowContextMenu,
      rowClassName,
      pagination?.pageSize,
      bodyClassName,
    ],
  )

  const paginationProps = useMemo(() => {
    if (!pagination) return null
    return {
      pagination,
      selectedCount,
      totalRows: pagination.totalRows ?? 0,
      className: paginationClassName,
    }
  }, [pagination, selectedCount, paginationClassName])

  return {
    showToolbar,
    toolbarProps,
    headerProps,
    bodyProps,
    paginationProps,
    containerClass,
    tableContainerClass,
    containerStyle,
  }
}
